### ISSUE TITLE
Differences in xsd and PDF

### ISSUE THREAD

**Issue by TatjanaKutzner** [nob140/CityGML3_ADE#2]
When comparing the XSD from https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/schemas/uro/1.5/urbanObject.xsd with the PDF from https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur/shiyouan1_5.pdf, I noticed the following differences:

Annex B Code lists for Urban Object Data
- No code lists are provided for the KeyValuePair attributes "key" and "codeValue"

Figure 1-2: 
- KeyValuePair contains the attribute "uri". The same attribute is called "uriValue" in the XML schema.
- The order of the attributes "codeValue" and "doubleValue" is vice verca in the XML schema.

Figure 1-3:
- The attribute "districtAndZoneType" is called "districtsAndZonesType" in the XML schema.

Figure 1-4:
- The association "trafficVolumeProperty" is called "trafficVolume" in the XML schema.

I assumed that the XML schema contains the correct information, when I created the UML model for CityGML 3.0.

**Comment by nob140** [comment]
Thanks for investigation and kind comments! You are correct. I will check your pull request tomorrow!

**Comment by nob140** [comment]
Thanks @TatjanaKutzner! I have uploaded codelists folder as well as schema.
