### ISSUE TITLE
I want to aggregate a declared new class to AbstractBuilding, but I don't know how to use ADE to define this aggregate relationship. Could you please tell me how to do it？thank you.

### ISSUE THREAD

**Issue by caidc** [nob140/CityGML3_ADE#3]
I want to aggregate a declared new class to AbstractBuilding, but I don't know how to use ADE to define this aggregate relationship.
Could you please tell me how to do it？thank you.
![微信截图_20220404225033](https://user-images.githubusercontent.com/26620090/161570610-d3c39178-ca14-43f4-96f3-1116d6e86ea2.png)

**Comment by nob140** [comment]
Dear caidc, sorry for not checking my repo...

Maybe, the BuildingUnderground below could be the answer for you.
https://github.com/opengeospatial/CityGML-3.0Encodings/blob/master/CityGML/annex-examples-ade.adoc

In case, please submit your isssue to the CityGML 3.0 GML Encoding repo directly.
https://github.com/opengeospatial/CityGML-3.0Encodings/issues
